# install nginx healthz in control plane
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest


- name: create kubernetes.default.svc.cluster.local
  ansible.builtin.shell: |
    cat > kubernetes.default.svc.cluster.local <<EOF
    server {
      listen      80;
      server_name kubernetes.default.svc.cluster.local;

      location /healthz {
        proxy_pass                    https://127.0.0.1:6443/healthz;
        proxy_ssl_trusted_certificate /var/lib/kubernetes/ca.pem;
      }
    }
    EOF
  
  args:
    chdir: /home/cloud_user


- name: move nginx config file
  ansible.builtin.shell: | 
    {
      sudo mv kubernetes.default.svc.cluster.local \
        /etc/nginx/sites-available/kubernetes.default.svc.cluster.local

      sudo ln -s /etc/nginx/sites-available/kubernetes.default.svc.cluster.local /etc/nginx/sites-enabled/
    }
  
  args:
    chdir: /home/cloud_user


- name: enable nginx service
  ansible.builtin.shell: |
    sudo systemctl restart nginx

    sudo systemctl enable nginx
  
