---
- name: install configure package
  hosts: all
  become: true
  gather_facts: true
  roles:
    - common

- name: install client tool
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - client-tool

- name: generate CA, key and data encryption file
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - certificate-authority
    - kube-config
    - data-encryption-config

- name: transfer config file to controller node
  hosts: controller_node
  become: true
  gather_facts: true
  roles:
    - distribute-CA-config

- name: distribute CA config to worker0
  hosts: worker
  become: true
  gather_facts: true
  tasks:
    - name: transfer CA config, kube config
      include_tasks:  distribute-CA-config/tasks/worker-CA.yml
      vars:
        - home_ca_folder: /home/vm1/kthw
        - host_name: 67c4ff09553c.mylabserver.com

- name: distribute CA config to worker1
  hosts: worker1
  become: true
  gather_facts: true
  tasks:
    - name: transfer CA config, kube config
      include_tasks:  distribute-CA-config/tasks/worker-CA.yml
      vars:
        - home_ca_folder: /home/vm1/kthw
        - host_name: 67c4ff09554c.mylabserver.com


- name: install etcd-cluster
  hosts: controller
  become: true
  gather_facts: true
  roles:
    - role: etcd-cluster
      vars: 
        ETCD_NAME: 67c4ff09551c.mylabserver.com
        INTERNAL_IP: 172.31.108.182
        INITIAL_CLUSTER: 67c4ff09551c.mylabserver.com=https://172.31.108.182:2380,67c4ff09552c.mylabserver.com=https://172.31.96.172:2380

- name: install etcd-cluster
  hosts: controller1
  become: true
  gather_facts: true
  roles:
    - role: etcd-cluster
      vars: 
        ETCD_NAME: 67c4ff09552c.mylabserver.com
        INTERNAL_IP: 172.31.96.172
        INITIAL_CLUSTER: 67c4ff09551c.mylabserver.com=https://172.31.108.182:2380,67c4ff09552c.mylabserver.com=https://172.31.96.172:2380

- name: enable etcd service
  hosts: controller_node
  become: true
  gather_facts: true 
  tasks:
    - name: enable service
      include_tasks:  etcd-cluster/tasks/enable-service.yml


- name: install kube-control-plane1
  hosts: controller1
  become: true
  gather_facts: true
  roles:
    - role: kubernetes-controllers
      vars: 
        INTERNAL_IP: 172.31.96.172

- name: install kube-control-plane0
  hosts: controller
  become: true
  gather_facts: true
  roles:
    - role: kubernetes-controllers
      vars: 
        INTERNAL_IP: 172.31.108.182

- name: enable kube control plane service
  hosts: controller_node
  become: true
  gather_facts: true 
  tasks:
    - name: enable service
      include_tasks:  kubernetes-controllers/tasks/enable-services.yml


- name: enable nginx healthz
  hosts: controller_node
  become: true
  gather_facts: true 
  tasks:
    - name: enable service
      include_tasks:  kubernetes-controllers/tasks/nginx-http.yml


- name: RBAC for Kubelet Authorization
  hosts: controller_node
  become: true
  gather_facts: true 
  tasks:
    - name: enable service
      include_tasks:  kubernetes-controllers/tasks/setup-RBAC.yml


- name: config loadbalancer
  hosts: nginx_lb
  become: true
  gather_facts: true 
  roles:
    - nginx-loadbalancer



- name: install kubernetes worker
  hosts: worker
  become: true
  gather_facts: true 
  roles:
    - role: kubernetes-worker
      vars: 
        POD_CIDR: 172.31.107.240/20
        HOSTNAME: 67c4ff09553c.mylabserver.com


- name: install kubernetes worker
  hosts: worker1
  become: true
  gather_facts: true 
  roles:
    - role: kubernetes-worker
      vars: 
        POD_CIDR: 172.31.107.166/20
        HOSTNAME: 67c4ff09554c.mylabserver.com

- name: start services kubernetes worker
  hosts: worker_node
  become: true
  gather_facts: true
  tasks:
    - name: enable service
      include_tasks:  kubernetes-worker/tasks/enable-services.yml
