---
- name: install configure package
  hosts: all
  become: true
  gather_facts: true
  roles:
    - common

- name: install client tool
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - client-tool
