---


- name: install kubernetes worker
  hosts: worker
  become: true
  gather_facts: true 
  roles:
    - role: kubernetes-worker
      vars: 
        POD_CIDR: 172.31.107.30/20
        HOSTNAME: 67c4ff09553c.mylabserver.com


- name: install kubernetes worker
  hosts: worker1
  become: true
  gather_facts: true 
  roles:
    - role: kubernetes-worker
      vars: 
        POD_CIDR: 172.31.97.112/20
        HOSTNAME: 67c4ff09554c.mylabserver.com

- name: start services kubernetes worker
  hosts: worker_node
  become: true
  gather_facts: true
  tasks:
    - name: enable service
      include_tasks:  kubernetes-worker/tasks/enable-services.yml