---
# tasks file for roles/nginx-loadbalancer
- name: allow port 6443
  ansible.builtin.shell: ufw allow 6443


- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest


- name: enable nginx
  ansible.builtin.shell: sudo systemctl enable nginx

- name: create /etc/nginx/tcpconf.d 
  ansible.builtin.shell: sudo mkdir -p /etc/nginx/tcpconf.d

- name: Add line to nginx.conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    line: "include /etc/nginx/tcpconf.d/*;"
    insertafter: EOF


- name: create /etc/nginx/tcpconf.d 
  ansible.builtin.shell: |
    cat << EOF | sudo tee /etc/nginx/tcpconf.d/kubernetes.conf
    stream {
        upstream kubernetes {
            server {{CONTROLLER0_IP}}:6443;
            server {{CONTROLLER1_IP}}:6443;
        }

        server {
            listen 6443;
            listen 443;
            proxy_pass kubernetes;
        }
    }
    EOF


- name: reload nginx
  ansible.builtin.shell: sudo nginx -s reload


